<?php

namespace CoreBundle\Repository;
use CoreBundle\Entity;

/**
 * TblLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblLogsRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
     * Inserta un nuevo registro en la tabla de log con los datos recibidos por parámetro
     *
     */	
	public function newRecord($user_logged, $table_name, $action_type, $column_name, $field_id, $old_value){
		
		$manager = $this->getEntityManager();
		$log_object = new Entity\TblLogs();
		
		$log_object->setUser($user_logged);
		$log_object->setTableName($table_name);
		$log_object->setActionType($action_type);
		$log_object->setColumnName($column_name);
		$log_object->setFieldId($field_id);
		$log_object->setOldValue($old_value);
		$log_object->setDate(new \DateTime("now"));
		
		$manager->persist($log_object);
		$manager->flush();
		
	}
	
	/**
     * Persiste un objeto TblLogs para posteriormente insertar un nuevo registro en la tabla de log con los datos recibidos por parámetro
     *
     */	
	public function setRecord($user_logged, $table_name, $action_type, $column_name, $field_id, $old_value){
		
		$manager = $this->getEntityManager();
		$log_object = new Entity\TblLogs();
		
		$log_object->setUser($user_logged);
		$log_object->setTableName($table_name);
		$log_object->setActionType($action_type);
		$log_object->setColumnName($column_name);
		$log_object->setFieldId($field_id);
		$log_object->setOldValue($old_value);
		$log_object->setDate(new \DateTime("now"));
		
		$manager->persist($log_object);
		
	}
}
