# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        CoreBundle\Entity\TblUsers:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity: 
                class: CoreBundle:TblUsers
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
#            provider: in_memory
            provider: user_db_provider
            form_login:
                login_path: /front/security/login
                check_path: /front/security/login
            logout:
                path: /front/security/logout
                target: /front/security/login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
                
    access_control:
        # cualquier usuario puede acceder al formulario de login
        - {path: ^/front/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY} 
        # sólo los usuarios con permisos de administrador pueden acceder al backoffice
        - {path: ^/admin, roles: ROLE_ADMIN}
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER            
        ROLE_SUPER_ADMIN: ROLE_ADMIN
