CoreBundle\Entity\TblCategory:
    type: entity
    table: tbl_category
    indexes:
        fk_category_category_group_idx:
            columns:
                - category_group_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        budgeted:
            type: float
            nullable: false
            precision: 11
            scale: 2
            options:
                default: '0.00'
        activity:
            type: float
            nullable: false
            precision: 11
            scale: 2
            options:
                default: '0.00'
        available:
            type: float
            nullable: false
            precision: 11
            scale: 2
            options:
                default: '0.00'
        hasGoal:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: has_goal
        goal:
            type: float
            nullable: true
            precision: 11
            scale: 2
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        createdOn:
            type: datetime
            nullable: false
            column: created_on
        deletedOn:
            type: datetime
            nullable: false
            column: deleted_on
    manyToOne:
        categoryGroup:
            targetEntity: TblCategoryGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_group_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
