CoreBundle\Entity\TblCategoryGroup:
    type: entity
    table: tbl_category_group
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
    manyToMany:
        user:
            targetEntity: TblUsers
            cascade: {  }
            fetch: LAZY
            mappedBy: categoryGroup
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
