CoreBundle\Entity\TblMonthlySummary:
    type: entity
    table: tbl_monthly_summary
    indexes:
        fk_summary_users_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        summaryMonth:
            type: date
            nullable: false
            column: summary_month
        fundsForMonth:
            type: float
            nullable: false
            precision: 11
            scale: 2
            options:
                default: '0.00'
            column: funds_for_month
        overspentLastMonth:
            type: float
            nullable: false
            precision: 11
            scale: 2
            options:
                default: '0.00'
            column: overspent_last_month
        budgetedMonth:
            type: float
            nullable: false
            precision: 11
            scale: 2
            options:
                default: '0.00'
            column: budgeted_month
    manyToOne:
        user:
            targetEntity: TblUsers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
