CoreBundle\Entity\TblPayees:
    type: entity
    table: tbl_payees
    indexes:
        fk_payees_users_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
            options:
                default: '1'
        createdOn:
            type: datetime
            nullable: false
            column: created_on
    manyToOne:
        user:
            targetEntity: TblUsers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
