CoreBundle\Entity\TblUsers:
    type: entity
    table: tbl_users
    repositoryClass: CoreBundle\Repository\TblUsersRepository
    indexes:
        fk_users_roles_idx:
            columns:
                - role_id
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        lastName:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: last_name
        email:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createdOn:
            type: datetime
            nullable: false
            column: created_on
    manyToOne:
        role:
            targetEntity: TblRoles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
                    nullable: false
            orphanRemoval: false
    manyToMany:
        categoryGroup:
            targetEntity: TblCategoryGroup
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: user
            joinTable:
                name: tbl_rel_users_category_group
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: category_group_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
