#front_homepage:
#    path:     /
#    defaults: { _controller: FrontBundle:Default:index }
    
security:
    resource: "@FrontBundle/Resources/config/routing/security.yml"
    prefix: /security
    
users:
    resource: "@FrontBundle/Resources/config/routing/user.yml"
    prefix: /users
